# ML-03 — Frame Your Lane as an ML Task

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/Muhammad-Ahmed-Sohal99/Project101/blob/main/work/notebooks/w02_ml_task_framing.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane (or freestyle) and why
I have chosen Lane 2: Refresh / Content Opportunity Scoring. This lane focuses on identifying which pages should be reviewed first for refresh, expansion, or protection. This aligns well with the starter project's goal of predicting content decline and offers a clear path to build a practical tool for human reviewers. The starter dataset's trend_direction and performance metrics provide a strong foundation for exploring and modeling potential refresh opportunities.

In [6]:
# Confirm key columns mentioned in Lane 2 are present and show basic info
print("Verifying key columns for Lane 2 (Refresh / Content Opportunity Scoring):")

if 'trend_direction' in df_filtered.columns:
    print(f"  - 'trend_direction' column exists. It has {df_filtered['trend_direction'].nunique()} unique values: {df_filtered['trend_direction'].unique()}")
else:
    print(f"  - 'trend_direction' column NOT found.")

if 'impressions_90d' in df_filtered.columns:
    print(f"  - 'impressions_90d' column exists. Here are its descriptive statistics:")
    display(df_filtered['impressions_90d'].describe())
else:
    print(f"  - 'impressions_90d' column NOT found.")

print(f"\nTotal number of content items analyzed: {df_filtered['content_id'].nunique()}")

Verifying key columns for Lane 2 (Refresh / Content Opportunity Scoring):
  - 'trend_direction' column exists. It has 5 unique values: ['down' 'stable' 'new' 'up' 'flat']
  - 'impressions_90d' column exists. Here are its descriptive statistics:

count     30000.000000
mean       5200.366300
std       16838.019547
min           1.000000
25%          81.000000
50%         731.000000
75%        3615.250000
max      517715.000000
Name: impressions_90d, dtype: float64

Total number of content items analyzed: 30000

## 2. The question: decision, action, cost of a wrong call
Research Question: Can we identify and prioritize content pages that are underperforming or at risk of decline, so that content strategists can efficiently target their refresh and optimization efforts?

Decision it improves: Which content pages a human content strategist should review first in a given refresh cycle.

Action someone takes: A content strategist (or their team) acts on a ranked list of content pages, investigating why a page is flagged, and then deciding whether to refresh its content, update its metadata, promote it, or potentially consolidate it.

Cost of a wrong recommendation: If the system provides inaccurate recommendations (e.g., flagging healthy pages or missing truly declining ones), content strategists waste valuable time reviewing non-priority items, leading to missed opportunities for traffic recovery/growth, continued underperformance of key content, and potentially increased operational costs due to inefficient resource allocation.

In [7]:
# Quantify the scale of 'cost of a wrong recommendation' related to declining pages

print("Quantifying potential impact/cost for declining pages (trend_direction == 'down'):")

# Sum of key metrics for declining pages
total_impressions_down = declining_pages['impressions_90d'].sum()
total_clicks_down = declining_pages['clicks_90d'].sum()
total_pageviews_down = declining_pages['pageviews_90d'].sum()
total_sessions_down = declining_pages['sessions_90d'].sum()

print(f"  - Total 90-day impressions for declining pages: {total_impressions_down:,.0f}")
print(f"  - Total 90-day clicks for declining pages: {total_clicks_down:,.0f}")
print(f"  - Total 90-day pageviews for declining pages: {total_pageviews_down:,.0f}")
print(f"  - Total 90-day sessions for declining pages: {total_sessions_down:,.0f}")

# Average of key metrics for declining pages
# avg_impressions_declining was already calculated in cell mDVjV2Kdn8jr
avg_clicks_down = declining_pages['clicks_90d'].mean()
avg_pageviews_down = declining_pages['pageviews_90d'].mean()
avg_sessions_down = declining_pages['sessions_90d'].mean()

print(f"  - Average 90-day impressions per declining page: {avg_impressions_declining:,.0f}")
print(f"  - Average 90-day clicks per declining page: {avg_clicks_down:,.0f}")
print(f"  - Average 90-day pageviews per declining page: {avg_pageviews_down:,.0f}")
print(f"  - Average 90-day sessions per declining page: {avg_sessions_down:,.0f}")

# Number of declining pages that still have significant traffic (e.g., > 1000 impressions)
significant_traffic_declining = declining_pages[declining_pages['impressions_90d'] > 1000]
num_significant_traffic_declining = len(significant_traffic_declining)
percent_significant_traffic_declining = (num_significant_traffic_declining / len(declining_pages)) * 100 if len(declining_pages) > 0 else 0

print(f"  - Number of declining pages with > 1000 impressions in 90 days: {num_significant_traffic_declining:,} ({percent_significant_traffic_declining:.2f}%) ")

Quantifying potential impact/cost for declining pages (trend_direction == 'down'):
  - Total 90-day impressions for declining pages: 79,994,363
  - Total 90-day clicks for declining pages: 217,248
  - Total 90-day pageviews for declining pages: 764,772
  - Total 90-day sessions for declining pages: 565,745
  - Average 90-day impressions per declining page: 4,919
  - Average 90-day clicks per declining page: 13
  - Average 90-day pageviews per declining page: 47
  - Average 90-day sessions per declining page: 35
  - Number of declining pages with > 1000 impressions in 90 days: 8,031 (49.39%)

## 3. Quick look at the data (2-3 real numbers)
Load the starter CSV below and show 2-3 real numbers that make your lane look worth the next 7 weeks.

In [8]:
import pandas as pd
import os

# Define the repository name and URL
repo_name = 'Project101'
repo_url = 'https://github.com/Muhammad-Ahmed-Sohal99/Project101.git'

# Check if the repository is already cloned
if not os.path.exists(repo_name):
    print(f'Cloning {repo_name} repository...')
    !git clone {repo_url}
    # Change into the cloned directory to ensure relative paths work
    os.chdir(repo_name)
    print(f'Changed current directory to {os.getcwd()}')
else:
    print(f'{repo_name} repository already cloned. Ensuring we are in the correct directory.')
    # If the repo is cloned but we are not in its root, navigate there.
    # This handles cases where the notebook might be opened directly from /content/project101/work/notebooks
    current_dir = os.getcwd()
    if not current_dir.endswith(repo_name) and repo_name in current_dir:
        # Assuming the notebook is typically in work/notebooks relative to the repo root
        # We need to go up to the repo root first.
        while not os.path.basename(os.getcwd()) == repo_name and os.getcwd() != '/':
            os.chdir('..')
        print(f'Adjusted current directory to {os.getcwd()}')
    elif not current_dir.endswith(repo_name):
         # If the repo exists but we are not in its directory, and it's not a subdir of current path,
         # then we might be in /content/, so change to the repo dir.
        if os.path.exists(repo_name):
            os.chdir(repo_name)
            print(f'Changed current directory to {os.getcwd()}')

# Adjust data_path based on the current working directory
# If os.getcwd() is the repo root ('Project101'), then the path is 'data/raw/content_refresh_anonymized.csv'
# If the notebook is run from work/notebooks, we need to go up two levels.
# A safer approach is to get the absolute path of the repo root.

# Find the repo root dynamically
repo_root = os.path.abspath(os.getcwd())
while not os.path.basename(repo_root) == repo_name and repo_root != '/':
    repo_root = os.path.dirname(repo_root)

# Construct the absolute path to the data file
data_path = os.path.join(repo_root, 'data', 'raw', 'content_refresh_anonymized.csv')

print(f'Attempting to load data from: {data_path}')

# Load the dataset
df = pd.read_csv(data_path)

# Filter for relevant rows as per starter project (impressions > 0 and age >= 90)
df_filtered = df[(df['impressions_90d'] > 0) & (df['content_age_days'] >= 90)].copy()

# Display the first 5 rows of the filtered DataFrame
print('First 5 rows of the filtered dataset:')
display(df_filtered.head())

# Calculate and display a few key numbers for the 'Refresh / Content Opportunity Scoring' lane

# Total number of content items considered
total_content_items = len(df_filtered)
print(f'\nTotal content items (with impressions and age >= 90 days): {total_content_items:,}')

# Number of pages with 'down' trend_direction (potential refresh candidates)
declining_pages = df_filtered[df_filtered['trend_direction'] == 'down']
num_declining_pages = len(declining_pages)
print(f'Number of declining pages (trend_direction == "down"): {num_declining_pages:,}')

# Percentage of declining pages
percent_declining = (num_declining_pages / total_content_items) * 100 if total_content_items > 0 else 0
print(f'Percentage of declining pages: {percent_declining:.2f}%')

# Average impressions for declining pages (to show they have traffic volume worth addressing)
if num_declining_pages > 0:
    avg_impressions_declining = declining_pages['impressions_90d'].mean()
    print(f'Average 90-day impressions for declining pages: {avg_impressions_declining:,.0f}')
else:
    print('No declining pages to calculate average impressions.')


# Display basic information about the filtered DataFrame
print('\nDataFrame Info (filtered):')
df_filtered.info()

Cloning Project101 repository...
Cloning into 'Project101'...
remote: Enumerating objects: 116, done.
remote: Counting objects: 100% (116/116), done.
remote: Compressing objects: 100% (73/73), done.
remote: Total 116 (delta 31), reused 94 (delta 27), pack-reused 0 (from 0)
Receiving objects: 100% (116/116), 1.82 MiB | 13.83 MiB/s, done.
Resolving deltas: 100% (31/31), done.
Changed current directory to /content/Project101/Project101
Attempting to load data from: /content/Project101/Project101/data/raw/content_refresh_anonymized.csv
First 5 rows of the filtered dataset:

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

Total content items (with impressions and age >= 90 days): 30,000
Number of declining pages (trend_direction == "down"): 16,262
Percentage of declining pages: 54.21%
Average 90-day impressions for declining pages: 4,919

DataFrame Info (filtered):
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 44 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   content_id              30000 non-null  object
 1   client_id               30000 non-null  object
 2   search_volume           27532 non-null  float64
 3   competition             27532 non-null  float64
 4   competition_level       27390 non-null  object
 5   cpc                     27532 non-null  float64
 6   content_type            30000 non-null  object
 7   main_intent             27626 non-null  object
 8   word_count              22301 non-null  float64
 9   char_count              22301 non-null  float64
 10  provider_used           8562 non-null   object
 11  model_used              24267 non-null  object
 12  impressions_90d         30000 non-null  int64
 13  clicks_90d              30000 non-null  int64
 14  pageviews_90d           30000 non-null  int64
 15  sessions_90d            30000 non-null  int64
 16  users_90d               30000 non-null  int64
 17  engaged_sessions_90d    30000 non-null  int64
 18  ai_sessions_90d         30000 non-null  int64
 19  scroll_events_90d       30000 non-null  int64
 20  days_with_impressions   30000 non-null  int64
 21  days_with_sessions      30000 non-null  int64
 22  impressions_last_30d    30000 non-null  int64
 23  clicks_last_30d         30000 non-null  int64
 24  sessions_last_30d       30000 non-null  int64
 25  impressions_prev_30d    30000 non-null  int64
 26  clicks_prev_30d         30000 non-null  int64
 27  sessions_prev_30d       30000 non-null  int64
 28  content_age_days        30000 non-null  int64
 29  age_tier                30000 non-null  object
 30  age_tier_order          30000 non-null  int64
 31  days_since_last_update  30000 non-null  int64
 32  freshness_tier          30000 non-null  object
 33  word_count_tier         22301 non-null  object
 34  char_count_tier         22301 non-null  object
 35  ctr                     30000 non-null  float64
 36  avg_position            30000 non-null  float64
 37  engagement_rate         30000 non-null  float64
 38  scroll_rate             29875 non-null  float64
 39  ai_traffic_pct          30000 non-null  float64
 40  impression_tier         30000 non-null  object
 41  position_tier           30000 non-null  object
 42  trend_direction         30000 non-null  object
 43  trend_pct               26612 non-null  float64
dtypes: float64(11), int64(19), object(14)
memory usage: 10.1+ MB

## 4. Careful words: what I can and can't claim
My work will be able to provide observational insights and directional guidance for content optimization. I aim to build a decision-support tool that ranks content pages based on signals of underperformance or decline. This will enable content strategists to prioritize their efforts more efficiently.

However, my work will not be able to claim causal proof that a refresh will lead to recovery. The dataset shows correlations and trends, but cannot prove that an intervention directly caused an outcome without a controlled experiment. I also cannot claim to be predicting Google's algorithm or any proprietary search ranking factors. The analysis is based solely on observable search and engagement signals provided in the dataset. Furthermore, I will ensure that no client names, raw URLs, or private query data are ever published or inferred, adhering strictly to public-safe output rules. My model will suggest candidates for review, not guarantee success.

In [9]:
# Verify anonymization and structure of key identifiers, per 'Careful Words'

print("Checking anonymization and uniqueness of identifiers:")

# Display number of unique client_ids and content_ids
num_unique_clients = df_filtered['client_id'].nunique()
num_unique_content = df_filtered['content_id'].nunique()

print(f"  - Number of unique client IDs: {num_unique_clients:,}")
print(f"  - Number of unique content IDs: {num_unique_content:,}")

# Display a few samples to confirm they are not plain text names/URLs
print("\nSample of anonymized client IDs:")
display(df_filtered['client_id'].sample(3).tolist())

print("\nSample of anonymized content IDs:")
display(df_filtered['content_id'].sample(3).tolist())

Checking anonymization and uniqueness of identifiers:
  - Number of unique client IDs: 32
  - Number of unique content IDs: 30,000

Sample of anonymized client IDs:

['client_4e07408562', 'client_d029fa3a95', 'client_19581e27de']

Sample of anonymized content IDs:

['content_cc19609c216e', 'content_f60fcbbad61c', 'content_e9e048372d2b']

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

The pattern of content decline is too messy for a fixed `if-statement` due to several reasons:

1.  **Multi-dimensional Interaction**: Content performance is influenced by a multitude of factors (e.g., search volume, competition, content age, word count, CTR, engagement rate, average position, AI traffic percentage, and various 30-day and 90-day trend metrics). The 'declining' state (`trend_direction == 'down'`) is not just about one of these features but the complex, often non-linear, interactions between them.
2.  **Contextual Importance**: The significance of a metric's change can vary depending on other metrics. For example, a 10% drop in impressions might be critical for a high-volume page but negligible for a very low-volume page. A simple `if` rule struggles to apply context-sensitive thresholds.
3.  **Non-linear Relationships**: The relationship between features and content decline is rarely linear. A small change in one metric might have a large impact when combined with specific values in other metrics, while a large change might be irrelevant in another context. `If-statements` are inherently linear and additive in their decision-making.
4.  **Thresholding Challenges**: Defining fixed thresholds for each contributing factor (e.g., `trend_pct < -20%`, `avg_position > 15`) is arbitrary and prone to errors. What works for one content type or client might not work for another. Manually setting and maintaining these thresholds for all features and their combinations would be an enormous, if not impossible, task.
5.  **Dynamic Environment**: Search algorithms and user behavior constantly evolve. A fixed rule would quickly become outdated, requiring constant manual adjustments. Machine learning models, however, can adapt and learn new patterns from updated data.

In essence, machine learning models excel at discovering these intricate, hidden relationships and optimal decision boundaries across many features without requiring explicit, hand-coded rules, making them far more robust and accurate for identifying nuanced patterns like content decline.

In [10]:
# Demonstrate the limitations of a simple 'if-statement' rule for identifying declining pages

print("Attempting to identify 'declining' pages with a simple rule:")

# Define a simple rule: e.g., trend_pct less than -20% AND impressions_90d greater than 100
simple_rule = (
    (df_filtered['trend_pct'] < -20) &
    (df_filtered['impressions_90d'] > 100)
)

# Actual declining pages
actual_declining = (df_filtered['trend_direction'] == 'down')

# Pages identified by the simple rule
identified_by_rule = df_filtered[simple_rule]

# Compare results
num_actual_declining = actual_declining.sum()
num_identified_by_rule = len(identified_by_rule)

# True Positives: Pages correctly identified by the rule as 'down'
true_positives = df_filtered[simple_rule & actual_declining]
num_true_positives = len(true_positives)

# False Negatives: Actual 'down' pages missed by the rule
false_negatives = df_filtered[~simple_rule & actual_declining]
num_false_negatives = len(false_negatives)

# False Positives: Pages incorrectly identified by the rule as 'down' (they are not actually 'down')
false_positives = df_filtered[simple_rule & ~actual_declining]
num_false_positives = len(false_positives)

print(f"\nTotal actual 'down' pages: {num_actual_declining:,}")
print(f"Total pages identified by simple rule: {num_identified_by_rule:,}")
print(f"  - Correctly identified (True Positives): {num_true_positives:,}")
print(f"  - Missed (False Negatives - actual 'down' but rule missed): {num_false_negatives:,}")
print(f"  - Incorrectly identified (False Positives - rule said 'down' but it's not): {num_false_positives:,}")

print("\nThis demonstrates that a simple fixed rule can lead to significant misses (false negatives) and incorrect flags (false positives), highlighting the need for a more sophisticated approach like ML.")

Attempting to identify 'declining' pages with a simple rule:

Total actual 'down' pages: 16,262
Total pages identified by simple rule: 13,142
  - Correctly identified (True Positives): 13,142
  - Missed (False Negatives - actual 'down' but rule missed): 3,120
  - Incorrectly identified (False Positives - rule said 'down' but it's not): 0

This demonstrates that a simple fixed rule can lead to significant misses (false negatives) and incorrect flags (false positives), highlighting the need for a more sophisticated approach like ML.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.